### PR TITLE
fix #48 return poped element on arr_pop

### LINKED ISSUE #48: JSON.ARRPOP should return the poped object and not the leftover
Wrong:
```bash
127.0.0.1:6379> json.set arr . '[0,1,2,3,4]'
OK
127.0.0.1:6379> JSON.ARRPOP arr . 4
"[0,1,2,3]"
```

Right:
```bash
127.0.0.1:6379> json.set arr . '[0,1,2,3,4]'
OK
127.0.0.1:6379> JSON.ARRPOP arr . 4
"4"
```

### PR DESCRIPTION
**Pull request by gkorland**

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -520,13 +520,15 @@ fn json_arr_pop(ctx: &Context, args: Vec<String>) -> RedisResult {
     let key = ctx.open_key_writable(&key);
     let mut res = Value::Null;
 
-    key.get_value::<RedisJSON>(&REDIS_JSON_TYPE)?
+    let _: RedisResult = key
```
Comment (gavrie) [inline src/lib.rs]: It seems like you're ignoring any error that could occur (such as the `nonexistent_key`), since the result is thrown away with the `let _`.

Instead, I'd suggest the following code. Note the question mark at the end to handle the error. 
It also gets rid of the unnecessary mapping of the result value (which is unused) and therefore also doesn't require the explicit type annotation:

```
    key.get_value::<RedisJSON>(&REDIS_JSON_TYPE)?
        .ok_or_else(RedisError::nonexistent_key)
        .and_then(|doc| {
            doc.value_op(&path, |value| do_json_arr_pop(index, &mut res, value))
                .map_err(|e| e.into())
        })?;
```

**Review by gavrie — CHANGES_REQUESTED** [review]

File: src/lib.rs (hunk 1 above)
Comment (gkorland) [reply src/lib.rs]: fixed
